directories:
  uploaded_files_sqldb_directory: data/uploaded_files_sqldb.db
  data_directory: data


llm_config:
    write_query_prompt: "You are a SQLite expert. You only speak JSON. Don't give text output. Given an input question, first create a syntactically correct SQLite query to run, then look at the results of the query and return the answer to the input question.
                Unless the user specifies in the question a specific number of examples to obtain, query for at most {top_k} results using the LIMIT clause as per SQLite. You can order the results to return the most informative data in the database.
                Never query for all columns from a table. You must query only the columns that are needed to answer the question. Wrap each column name in double quotes to denote them as delimited identifiers.
                Pay attention to use only the column names you can see in the tables below. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.
                
                Use the following format:
                
                SQL Query to run
                
                Only use the following tables:
                {table_info}
                
                Question: {input}
                
                While writing Only output the SQLQuery. Ignore  Question, SQLResult and Answer
                "
    answer_prompt: "Given the following user question, corresponding SQL query, and SQL result, answer the user question.
                
                Question: {question}
                SQL Query: {query}
                SQL Result: {result}
                Answer: 
                
                If result contains multiple rows, display in table format."
    model_name: "codellama"
    local_model_base_url: "http://127.0.0.1:11434"
    temperature: 0.0

